### ISSUE TITLE
Hi, In the UIEB dataset, did you resize the image when calculating SSIM and PSNR? If ''resize'' is done, what is the size?

### ISSUE THREAD

**Issue by taotaoandxfj** [pksvision/Deep-WaveNet-Underwater-Image-Restoration#2]
Hi, In the UIEB dataset, did you resize the image when calculating SSIM and PSNR? If ''resize'' is done, what is the size?

**Comment by pksvision** [comment]
Hi, 
No, for UIEB, we have not resized the images while calculating SSIM and PSNR.
