### ISSUE TITLE
HI, HI, In UIEB dataset, I used your "checkpoints-netG_295.pt" to test the 90 images I selected many times, but the SSIM and PSNR were 0.91 and 25.37 respectively (0.80 and 21.57 in Table 2). So, can you share your selected test set? Or do I have a wrong understanding of the division of the data set? please!

### ISSUE THREAD

**Issue by taotaoandxfj** [pksvision/Deep-WaveNet-Underwater-Image-Restoration#3]
HI, In UIEB dataset, I used your "checkpoints-netG_295.pt" to test the 90 images I selected many times, but the SSIM and PSNR were 0.91 and 25.37 respectively (0.80 and 21.57 in Table 2). So, can you share your selected test set? Or do I have a wrong understanding of the division of the data set? please!

**Comment by pksvision** [comment]
Hi,

It has already been shared with the description in README.md. 
<Datasets Preparation / To test the Deep WaveNet on UIEB and Challenging-60 datasets/>

For UIEB, we opted five-fold cross validation scheme and reported the mean results across the folds. For reference, one of the fold has been shared as mentioned above. 

You can also create your own folds or single-split sets, train, and test your own checkpoint(s). Let me know the results you got. I'm keeping this issue open.  

Thanks for reaching out.

**Comment by dingyan1478** [comment]
> HI, In UIEB dataset, I used your "checkpoints-netG_295.pt" to test the 90 images I selected many times, but the SSIM and PSNR were 0.91 and 25.37 respectively (0.80 and 21.57 in Table 2). So, can you share your selected test set? Or do I have a wrong understanding of the division of the data set? please!



> HI, In UIEB dataset, I used your "checkpoints-netG_295.pt" to test the 90 images I selected many times, but the SSIM and PSNR were 0.91 and 25.37 respectively (0.80 and 21.57 in Table 2). So, can you share your selected test set? Or do I have a wrong understanding of the division of the data set? please!

I'm sorry to bother you. I want to ask what your test environment is like. Why do I always display out of memory during testing!
If you can, could you please send me a copy of your test results? I really want to see the test results!
Look  forward to your reply!
My email: dingyan1478@163.com

**Comment by pksvision** [comment]
1. https://github.com/pksvision/Deep-WaveNet-Underwater-Image-Restoration/issues/4#issuecomment-904617973
2. You can refer the results from the google drive link given under the section "**To test the Deep WaveNet on UIEB and Challenging-60 datasets**" in readme file.
