### ISSUE TITLE
PSNR and MSE

### ISSUE THREAD

**Issue by wangdanxu** [pksvision/Deep-WaveNet-Underwater-Image-Restoration#5]
Hi, In tabel Ⅳ, I calculated the value of PSNR and MSE , but I found it don't meet the formula : psnr=20*math.log10(255.0/rmse),do i have a wrong understanding of that?

**Comment by pksvision** [comment]
We have followed the implementation of PSNR using 

https://github.com/xahidbuffon/FUnIE-GAN/blob/8f934c834c94e007b00866186b9ee624dc2b7b69/Evaluation/imqual_utils.py#L66 

Table 4 shows ablation study and presents the achieved results using different cost functions on EUVP and UIEB datasets for the task of underwater image enhancement. You should get the similar results after sufficient training. I suggest to keep track of hyperparams and let it train for good number of iterations (atleast around the figure mentioned in the paper).
