### ISSUE TITLE
How can i Use it for my underwater images

### ISSUE THREAD

**Issue by aliman80** [pksvision/Deep-WaveNet-Underwater-Image-Restoration#7]
HI 
I am a Novice and trying to use your code for underwater images of other datasets. Can you guide me how to use your model for my datasets please with reference to coding.

**Comment by pksvision** [comment]
Hi @aliman80,

If you are willing to use it for image enhancement then please switch to uie_uieb directory and follow the specific details. 

Else if you want to perform image super-resolution, switch to super-resolution folder and follow the specific details. 

The particular steps to perform above operations are mentioned in Usage section.

Feel free to drop further queries here or via mail.

Thanks

**Comment by aliman80** [comment]
Thank you very much i will try the above steps if needed further guidance will contact you .

Thanks again for your positive reply
