### ISSUE TITLE
UIEB test set sharelink invalid

### ISSUE THREAD

**Issue by LOSKIw** [pksvision/Deep-WaveNet-Underwater-Image-Restoration#8]
Seems like the googledrive link of the UIEB test set is invalid somehow, got a 404 error, could you please renew the google drive sharing?
checked several times it doesn't look like to be my own connecting problem.

**Comment by pksvision** [comment]
Sure, drive quota might have exhausted. Give me sometime, I'll find and share with you.

**Comment by LOSKIw** [comment]
Thanks, that would be a great help.

**Comment by pksvision** [comment]
Hey, apologies for the late reply. 

I could not resolve, it might take some more time. 

Meanwhile, I would appreciate you if you can create your own split of train/test sets from UIEB and compare existing and our work (retrain). Pl let me know if you need anything else. 

Thanks,
